QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	-- Melee
	[GetHashKey('weapon_unarmed')] 				 = {['name'] = 'weapon_unarmed', 		['label'] = 'Fists', 				['maxammo'] = 50, ['ammotype'] = nil, ['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_dagger')] 				 = {['name'] = 'weapon_dagger', 		['label'] = 'Dagger', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_bat')] 					 = {['name'] = 'weapon_bat', 			['label'] = 'Bat', 					['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_bottle')] 				 = {['name'] = 'weapon_bottle', 		['label'] = 'Broken Bottle', 		['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_crowbar')] 				 = {['name'] = 'weapon_crowbar', 		['label'] = 'Crowbar', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_flashlight')] 			 = {['name'] = 'weapon_flashlight', 	['label'] = 'Flashlight', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_golfclub')] 			 = {['name'] = 'weapon_golfclub', 		['label'] = 'Golfclub', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_hammer')] 				 = {['name'] = 'weapon_hammer', 		['label'] = 'Hammer', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_hatchet')] 				 = {['name'] = 'weapon_hatchet', 		['label'] = 'Hatchet', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_knuckle')] 				 = {['name'] = 'weapon_knuckle', 		['label'] = 'Knuckle', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_knife')] 				 = {['name'] = 'weapon_knife', 			['label'] = 'Knife', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_machete')] 				 = {['name'] = 'weapon_machete', 		['label'] = 'Machete', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_switchblade')] 			 = {['name'] = 'weapon_switchblade', 	['label'] = 'Switchblade', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_nightstick')] 			 = {['name'] = 'weapon_nightstick', 	['label'] = 'Nightstick', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_wrench')] 				 = {['name'] = 'weapon_wrench', 		['label'] = 'Wrench', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_battleaxe')] 			 = {['name'] = 'weapon_battleaxe', 		['label'] = 'Battle Axe', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[GetHashKey('weapon_poolcue')] 				 = {['name'] = 'weapon_poolcue', 		['label'] = 'Poolcue', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_briefcase')] 			 = {['name'] = 'weapon_briefcase', 		['label'] = 'Briefcase', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_briefcase_02')] 		 = {['name'] = 'weapon_briefcase_02', 	['label'] = 'Briefcase', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_garbagebag')] 			 = {['name'] = 'weapon_garbagebag', 	['label'] = 'Garbage Bag', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_handcuffs')] 			 = {['name'] = 'weapon_handcuffs', 		['label'] = 'Handcuffs', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_bread')] 				 = {['name'] = 'weapon_bread', 			['label'] = 'Baquette', 			['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_stone_hatchet')] 		 = {['name'] = 'weapon_stone_hatchet', 	['label'] = 'Weapon Stone Hatchet', ['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	--[GetHashKey('weapon_radargun')] 				 = {['name'] = 'weapon_radargun', 		['label'] = 'Radar Gun', 				['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Really???'},
    -- Handguns
	[GetHashKey('weapon_pistol')] 				 = {['name'] = 'weapon_pistol', 		['label'] = 'Walther P99', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_pistol_mk2')] 			 = {['name'] = 'weapon_pistol_mk2', 	['label'] = 'Pistol Mk II', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_combatpistol')] 		 = {['name'] = 'weapon_combatpistol', 	['label'] = 'Combat Pistol', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_appistol')] 			 = {['name'] = 'weapon_appistol', 		['label'] = 'AP Pistol', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_stungun')] 				 = {['name'] = 'weapon_stungun', 		['label'] = 'Taser', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Died'},
	[GetHashKey('weapon_pistol50')] 			 = {['name'] = 'weapon_pistol50', 		['label'] = 'Pistol .50 Cal', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_snspistol')] 			 = {['name'] = 'weapon_snspistol', 		['label'] = 'SNS Pistol', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_snspistol_mk2')] 	     = {['name'] = 'weapon_snspistol_mk2', 	['label'] = 'SNS Pistol MK2', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_heavypistol')] 			 = {['name'] = 'weapon_heavypistol', 	['label'] = 'Heavy Pistol', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_vintagepistol')] 		 = {['name'] = 'weapon_vintagepistol', 	['label'] = 'Vintage Pistol', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_flaregun')] 			 = {['name'] = 'weapon_flaregun', 		['label'] = 'Flare Gun', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Died'},
	[GetHashKey('weapon_marksmanpistol')] 		 = {['name'] = 'weapon_marksmanpistol', ['label'] = 'Marksman Pistol', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_revolver')] 			 = {['name'] = 'weapon_revolver', 		['label'] = 'Revolver', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_revolver_mk2')] 		 = {['name'] = 'weapon_revolver_mk2', 	['label'] = 'Violence', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_doubleaction')] 	     = {['name'] = 'weapon_doubleaction', 	['label'] = 'Double Action Revolver',	['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_raypistol')]			 = {['name'] = 'weapon_raypistol',		['label'] = 'Weapon Raypistol',			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_ceramicpistol')]		 = {['name'] = 'weapon_ceramicpistol', 	['label'] = 'Weapon Ceramicpistol',		['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_navyrevolver')]        	 = {['name'] = 'weapon_navyrevolver', 	['label'] = 'Weapon Navyrevolver',		['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_gadgetpistol')] 		 = {['name'] = 'weapon_gadgetpistol', 	['label'] = 'Weapon Gadgetpistol',		['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_stungun_mp')] 			 = {['name'] = 'weapon_stungun_mp', 	['label'] = 'Taser', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Died'},

    -- Submachine Guns
	[GetHashKey('weapon_microsmg')] 			 = {['name'] = 'weapon_microsmg', 		['label'] = 'Micro SMG', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_smg')] 				 	 = {['name'] = 'weapon_smg', 			['label'] = 'SMG', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_smg_mk2')] 				 = {['name'] = 'weapon_smg_mk2', 		['label'] = 'PD MP5 2', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_assaultsmg')] 			 = {['name'] = 'weapon_assaultsmg', 	['label'] = 'Assault SMG', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_combatpdw')] 			 = {['name'] = 'weapon_combatpdw', 		['label'] = 'Combat PDW', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_machinepistol')] 		 = {['name'] = 'weapon_machinepistol', 	['label'] = 'Tec-9', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_minismg')] 				 = {['name'] = 'weapon_minismg', 		['label'] = 'Mini SMG', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_raycarbine')]	         = {['name'] = 'weapon_raycarbine', 	['label'] = 'Weapon Raycarbine',	['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},

    -- Shotguns
	[GetHashKey('weapon_pumpshotgun')] 			 = {['name'] = 'weapon_pumpshotgun', 	 	['label'] = 'Pump Shotgun', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_pumpshotgun_mk2')]		 = {['name'] = 'weapon_pumpshotgun_mk2',	['label'] = 'Pumpshotgun MK2', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_sawnoffshotgun')] 		 = {['name'] = 'weapon_sawnoffshotgun', 	['label'] = 'Sawn-off Shotgun', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_assaultshotgun')] 		 = {['name'] = 'weapon_assaultshotgun', 	['label'] = 'Assault Shotgun', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_bullpupshotgun')] 		 = {['name'] = 'weapon_bullpupshotgun', 	['label'] = 'Bullpup Shotgun', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_musket')] 			     = {['name'] = 'weapon_musket', 			['label'] = 'Musket', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_heavyshotgun')] 		 = {['name'] = 'weapon_heavyshotgun', 	 	['label'] = 'Heavy Shotgun', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_dbshotgun')] 			 = {['name'] = 'weapon_dbshotgun', 		 	['label'] = 'Double-barrel Shotgun', 	['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_autoshotgun')] 			 = {['name'] = 'weapon_autoshotgun', 	 	['label'] = 'Auto Shotgun', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[GetHashKey('weapon_combatshotgun')]		 = {['name'] = 'weapon_combatshotgun', 		['label'] = 'Weapon Combatshotgun',		['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},

    -- Assault Rifles
	[GetHashKey('weapon_assaultrifle')] 		 = {['name'] = 'weapon_assaultrifle', 	 	['label'] = 'Assault Rifle', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_assaultrifle_mk2')] 	 = {['name'] = 'weapon_assaultrifle_mk2', 	['label'] = 'AK-47 MK2', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_carbinerifle')] 		 = {['name'] = 'weapon_carbinerifle', 	 	['label'] = 'Carbine Rifle', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [GetHashKey('weapon_carbinerifle_mk2')] 	 = {['name'] = 'weapon_carbinerifle_mk2', 	['label'] = 'PD 762', 						['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_advancedrifle')] 		 = {['name'] = 'weapon_advancedrifle', 	 	['label'] = 'Advanced Rifle', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_specialcarbine')] 		 = {['name'] = 'weapon_specialcarbine', 	['label'] = 'Special Carbine', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_specialcarbine_mk2')]	 = {['name'] = 'weapon_specialcarbine_mk2',	['label'] = 'Weapon Wpecialcarbine MK2',	['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_bullpuprifle')] 		 = {['name'] = 'weapon_bullpuprifle', 	 	['label'] = 'Bullpup Rifle', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_bullpuprifle_mk2')]		 = {['name'] = 'weapon_bullpuprifle_mk2', 	['label'] = 'Bull Puprifle MK2',			['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_compactrifle')] 		 = {['name'] = 'weapon_compactrifle', 	 	['label'] = 'Compact Rifle', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_militaryrifle')]		 = {['name'] = 'weapon_militaryrifle', 		['label'] = 'Weapon Militaryrifle',			['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [GetHashKey('weapon_heavyrifle')] 			 = {['name'] = 'weapon_heavyrifle', 	 	['label'] = 'Heavy Rifle', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},

    -- Light Machine Guns
	[GetHashKey('weapon_mg')] 					 = {['name'] = 'weapon_mg', 			['label'] = 'Machinegun', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[GetHashKey('weapon_combatmg')] 			 = {['name'] = 'weapon_combatmg', 		['label'] = 'Combat MG', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[GetHashKey('weapon_combatmg_mk2')]	 		 = {['name'] = 'weapon_combatmg_mk2', 	['label'] = 'Weapon Combatmg MK2',	['maxammo'] = 50, ['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[GetHashKey('weapon_gusenberg')] 			 = {['name'] = 'weapon_gusenberg', 		['label'] = 'Thompson SMG', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},

    -- Sniper Rifles
	[GetHashKey('weapon_sniperrifle')] 			 = {['name'] = 'weapon_sniperrifle', 	 	['label'] = 'Sniper Rifle', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[GetHashKey('weapon_heavysniper')] 			 = {['name'] = 'weapon_heavysniper', 	 	['label'] = 'Heavy Sniper', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[GetHashKey('weapon_heavysniper_mk2')]		 = {['name'] = 'weapon_heavysniper_mk2', 	['label'] = 'Weapon Heavysniper MK2',	['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[GetHashKey('weapon_marksmanrifle')] 		 = {['name'] = 'weapon_marksmanrifle', 	 	['label'] = 'Marksman Rifle', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[GetHashKey('weapon_marksmanrifle_mk2')]	 = {['name'] = 'weapon_marksmanrifle_mk2',	['label'] = 'Weapon Marksmanrifle MK2',	['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[GetHashKey('weapon_remotesniper')] 		 = {['name'] = 'weapon_remotesniper', 	 	['label'] = 'Remote Sniper', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER_REMOTE',	['damagereason'] = 'Sniped / Picked off / Scoped'},

    -- Heavy Weapons
	[GetHashKey('weapon_rpg')] 					 = {['name'] = 'weapon_rpg', 			      	['label'] = 'RPG', 						['maxammo'] = 50, ['ammotype'] = 'AMMO_RPG',				['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_grenadelauncher')] 		 = {['name'] = 'weapon_grenadelauncher', 	  	['label'] = 'Grenade Launcher', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_grenadelauncher_smoke')] = {['name'] = 'weapon_grenadelauncher_smoke',	['label'] = 'Smoke Grenade Launcher',	['maxammo'] = 50, ['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_minigun')] 				 = {['name'] = 'weapon_minigun', 		      	['label'] = 'Minigun', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_firework')] 			 = {['name'] = 'weapon_firework', 		 	  	['label'] = 'Firework Launcher', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_RPG',						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_railgun')] 				 = {['name'] = 'weapon_railgun', 		 	  	['label'] = 'Railgun', 					['maxammo'] = 50, ['ammotype'] = 'AMMO_RPG',					['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_hominglauncher')] 		 = {['name'] = 'weapon_hominglauncher', 	 	['label'] = 'Homing Launcher', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_STINGER',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_compactlauncher')] 		 = {['name'] = 'weapon_compactlauncher',  	  	['label'] = 'Compact Launcher', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_RPG',							['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_rayminigun')]			 = {['name'] = 'weapon_rayminigun', 		 	['label'] = 'Weapon Rayminigun',		['maxammo'] = 50, ['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
    [GetHashKey('weapon_emplauncher')] 			 = {['name'] = 'weapon_emplauncher', 			['label'] = 'EMP Launcher', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_EMPLAUNCHER',		['damagereason'] = 'Died'},

    -- Throwables
	[GetHashKey('weapon_grenade')] 		 = {['name'] = 'weapon_grenade', 		['label'] = 'Grenade', 			['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[GetHashKey('weapon_bzgas')] 		 = {['name'] = 'weapon_bzgas', 			['label'] = 'BZ Gas', 			['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Died'},
	[GetHashKey('weapon_molotov')] 		 = {['name'] = 'weapon_molotov', 		['label'] = 'Molotov', 			['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Torched / Flambeed / Barbecued'},
	[GetHashKey('weapon_stickybomb')] 	 = {['name'] = 'weapon_stickybomb', 	['label'] = 'C4', 				['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[GetHashKey('weapon_proxmine')] 	 = {['name'] = 'weapon_proxmine', 		['label'] = 'Proxmine Grenade', ['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[GetHashKey('weapon_snowball')] 	 = {['name'] = 'weapon_snowball', 		['label'] = 'Snowball', 		['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Died'},
	[GetHashKey('weapon_pipebomb')] 	 = {['name'] = 'weapon_pipebomb', 		['label'] = 'Pipe Bomb', 		['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[GetHashKey('weapon_ball')] 		 = {['name'] = 'weapon_ball', 			['label'] = 'Ball', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_BALL',		['damagereason'] = 'Died'},
	[GetHashKey('weapon_smokegrenade')]  = {['name'] = 'weapon_smokegrenade', 	['label'] = 'Smoke Grenade', 	['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Died'},
	[GetHashKey('weapon_flare')] 		 = {['name'] = 'weapon_flare', 			['label'] = 'Flare pistol', 	['maxammo'] = 50, ['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Died'},

    -- Miscellaneous
	[GetHashKey('weapon_petrolcan')] 			= {['name'] = 'weapon_petrolcan', 		 	['label'] = 'Petrol Can', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
	['gadget_parachute'] 			= {['name'] = 'gadget_parachute', 		 	['label'] = 'Parachute', 				['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Died'},
	[GetHashKey('weapon_fireextinguisher')] 	= {['name'] = 'weapon_fireextinguisher',	['label'] = 'Fire Extinguisher',		['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Died'},
	[GetHashKey('weapon_hazardcan')]			= {['name'] = 'weapon_hazardcan',			['label'] = 'Weapon Hazardcan',			['maxammo'] = 50, ['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
    [GetHashKey('weapon_fertilizercan')]		= {['name'] = 'weapon_fertilizercan',		['label'] = 'Fertilizer Can',			['maxammo'] = 50, ['ammotype'] = 'AMMO_FERTILIZERCAN',	['damagereason'] = 'Died'},
	[GetHashKey('weapon_barbed_wire')]			= {['name'] = 'weapon_barbed_wire',			['label'] = 'Barbed Wire',				['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Prodded'},
	[GetHashKey('weapon_drowning')]				= {['name'] = 'weapon_drowning',			['label'] = 'Drowning',					['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Died'},
	[GetHashKey('weapon_drowning_in_vehicle')]	= {['name'] = 'weapon_drowning_in_vehicle',	['label'] = 'Drowning in a Vehicle',	['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Died'},
	[GetHashKey('weapon_bleeding')]				= {['name'] = 'weapon_bleeding',			['label'] = 'Bleeding',					['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Bled out'},
	[GetHashKey('weapon_electric_fence')]		= {['name'] = 'weapon_electric_fence',		['label'] = 'Electric Fence',			['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Fried'},
	[GetHashKey('weapon_explosion')]			= {['name'] = 'weapon_explosion',			['label'] = 'Explosion',				['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[GetHashKey('weapon_fall')]					= {['name'] = 'weapon_fall',				['label'] = 'Fall',						['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Committed suicide'},
	[GetHashKey('weapon_exhaustion')]			= {['name'] = 'weapon_exhaustion',			['label'] = 'Exhaustion',				['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Died'},
	[GetHashKey('weapon_hit_by_water_cannon')]	= {['name'] = 'weapon_hit_by_water_cannon',	['label'] = 'Water Cannon',				['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Died'},
	[GetHashKey('weapon_rammed_by_car')]		= {['name'] = 'weapon_rammed_by_car',		['label'] = 'Rammed - Vehicle',			['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[GetHashKey('weapon_run_over_by_car')]		= {['name'] = 'weapon_run_over_by_car',		['label'] = 'Run Over - Vehicle',		['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[GetHashKey('weapon_heli_crash')]			= {['name'] = 'weapon_heli_crash',			['label'] = 'Heli Crash',				['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Helicopter Crash'},
	[GetHashKey('weapon_fire')]					= {['name'] = 'weapon_fire',				['label'] = 'Fire',						['maxammo'] = 50, ['ammotype'] = nil,						['damagereason'] = 'Torched / Flambeed / Barbecued'},

	-- Animals
	[GetHashKey('weapon_animal')]	= {['name'] = 'weapon_animal',	['label'] = 'Animal',	['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Mauled'},
    [GetHashKey('weapon_cougar')]	= {['name'] = 'weapon_cougar',	['label'] = 'Cougar',	['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Mauled'},

-- custom weapons

--[GetHashKey('weapon_shoe']	= {['name'] = 'weapon_shoe',	['label'] = 'Shoe',	['maxammo'] = 50, ['ammotype'] = nil,	['damagereason'] = 'Shit On'},

[GetHashKey('weapon_ak47')] 		 = {['name'] = 'weapon_ak47', 	 	['label'] = 'AK-47', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[GetHashKey('weapon_m70')] 		 = {['name'] = 'weapon_m70', 	 	['label'] = 'M70', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[GetHashKey('weapon_de')] 			 = {['name'] = 'weapon_de', 		['label'] = 'Desert Eagle', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[GetHashKey('weapon_fnx45')] 			 = {['name'] = 'weapon_fnx45', 		['label'] = 'FN FNX45', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	 ['caliber'] = '9mm',['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[GetHashKey('weapon_glock17')] 			 = {['name'] = 'weapon_glock17', 		['label'] = 'PD Glock 17', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL', ['caliber'] = '9mm',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[GetHashKey('weapon_m4')] 		 = {['name'] = 'weapon_m4', 	 	['label'] = 'PD M4A1', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	 ['caliber'] = '5.56',['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[GetHashKey('weapon_m9')] 			 = {['name'] = 'weapon_m9', 		['label'] = 'Beretta M9A3', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL', ['caliber'] = '9mm',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[GetHashKey('weapon_m1911')] 			 = {['name'] = 'weapon_m1911', 		['label'] = 'M1911', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL', ['caliber'] = '9mm',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[GetHashKey('weapon_uzi')] 			 = {['name'] = 'weapon_uzi', 		['label'] = 'UZI', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',	 ['caliber'] = 'SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
[GetHashKey('weapon_mac10')] 			 = {['name'] = 'weapon_mac10', 		['label'] = 'MAC-10', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',	 ['caliber'] = 'SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
[GetHashKey('weapon_mossberg')] 		 = {['name'] = 'weapon_mossberg', 	['label'] = 'Mossberg 500', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN', ['caliber'] = 'Buckshot',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
[GetHashKey('weapon_remington')] 		 = {['name'] = 'weapon_remington', 	['label'] = 'Remington 870', 		['maxammo'] = 50, ['ammotype'] = 'AMMO_SHOTGUN', ['caliber'] = 'Buckshot',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
[GetHashKey('weapon_scarh')] 		 = {['name'] = 'weapon_scarh', 	['label'] = 'PD SCAR-H', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[GetHashKey('weapon_shiv')] 				 = {['name'] = 'weapon_shiv', 			['label'] = 'Shiv', 				['maxammo'] = 50, ['ammotype'] = nil,	 ['caliber'] = 'Shiv',['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
[GetHashKey('weapon_katana')] 				 = {['name'] = 'weapon_katana', 			['label'] = 'Katana', 				['maxammo'] = 50, ['ammotype'] = nil, ['caliber'] = 'Katana',	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
[GetHashKey('weapon_sledgehammer')] 				 = {['name'] = 'weapon_sledgehammer', 			['label'] = 'Sledge Hammer', 				['maxammo'] = 50, ['ammotype'] = nil,	['caliber'] = 'Sledge',['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
[GetHashKey('weapon_ar15')] 		 = {['name'] = 'weapon_ar15', 	 	['label'] = 'PD AR-15', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[GetHashKey('weapon_mk14')] 		 = {['name'] = 'weapon_mk14', 	 	['label'] = 'PD MK14', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER', ['caliber'] = '50 Cal',	['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
[GetHashKey('weapon_huntingrifle')] 		 = {['name'] = 'weapon_huntingrifle', 	 	['label'] = 'Hunting Rifle', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER', ['caliber'] = '',	['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
[GetHashKey('weapon_mp9')] 			 = {['name'] = 'weapon_mp9', 		['label'] = 'MP9', 			['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		 ['caliber'] = '',['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
[GetHashKey('weapon_m110')] 		 = {['name'] = 'weapon_m110', 	 	['label'] = 'M110', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_SNIPER',	 ['caliber'] = '50 Cal',['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
[GetHashKey('weapon_hk416')] 		 = {['name'] = 'weapon_hk416', 	 	['label'] = 'HK-416', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},

	[GetHashKey('weapon_assaultrifle2')] 		 = {['name'] = 'weapon_assaultrifle2', 	 	['label'] = 'M 70', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_sniperrifle2')] 		 = {['name'] = 'weapon_sniperrifle2', 	 	['label'] = 'weapon_sniperrifle2', 				['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_shoe')] 		 = {['name'] = 'weapon_shoe', 	 	['label'] = 'weapon_shoe', 				['maxammo'] = 50, ['ammotype'] = nil, ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_nailgun')] 		 = {['name'] = 'weapon_nailgun', 	 	['label'] = 'weapon_nailgun', 				['maxammo'] = 50, ['ammotype'] =  'AMMO_PISTOL', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_brick')] 		 = {['name'] = 'weapon_brick', 	 	['label'] = 'weapon_brick', 				['maxammo'] = 50, ['ammotype'] =  nil, ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_cash')] 		 = {['name'] = 'weapon_cash', 	 	['label'] = 'weapon_cash', 				['maxammo'] = 50, ['ammotype'] =  nil, ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	
	[GetHashKey('weapon_glock')] 		 = {['name'] = 'weapon_glock', 	 	['label'] = 'weapon_glock', 				['maxammo'] = 50, ['ammotype'] =  'AMMO_PISTOL', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	
	[GetHashKey('weapon_microsmg3')] 		 = {['name'] = 'weapon_microsmg3', 	 	['label'] = 'weapon_microsmg3', 				['maxammo'] = 50, ['ammotype'] =  'AMMO_SMG', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_microsmg2')] 		 = {['name'] = 'weapon_microsmg2', 	 	['label'] = 'weapon_microsmg2', 				['maxammo'] = 50, ['ammotype'] =  'AMMO_SMG', ['caliber'] = '5.56',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	
	[GetHashKey('weapon_gepard')] 		 		 = {['name'] = 'weapon_gepard', 	 		['label'] = 'GEPARD', 						['weapontype'] = 'Assault Rifle',	['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_g18c')] 				 = {['name'] = 'weapon_g18c', 			['label'] = 'GLOCK-18C', 				['weapontype'] = 'Pistol',	['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_mp5')] 			 		 = {['name'] = 'weapon_mp5', 			['label'] = 'MP5', 					['weapontype'] = 'Submachine Gun',	['maxammo'] = 50, ['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[GetHashKey('weapon_dp9')] 				 	 = {['name'] = 'weapon_dp9', 			['label'] = 'DP9', 				   	['weapontype'] = 'Pistol',			['maxammo'] = 50, ['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[GetHashKey('weapon_m67')] 		        	= {['name'] = 'weapon_m67', 			['label'] = 'M67', 				['weapontype'] = 'Throwable',	['maxammo'] = 50, ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[GetHashKey('weapon_groza')] 		 		 = {['name'] = 'weapon_groza', 	 		['label'] = 'GROZA', 				['weapontype'] = 'Assault Rifle',	['maxammo'] = 50, ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[GetHashKey('weapon_sword')] 			     = {['name'] = 'weapon_sword', 		['label'] = 'SWORD', 			['weapontype'] = 'Melee',	['maxammo'] = 50, ['ammotype'] = nil, ['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
    [GetHashKey('weapon_krambit')] 			 	 = {['name'] = 'weapon_krambit', 		['label'] = 'KRAMBIT', 				['weapontype'] = 'Melee',	['maxammo'] = 50, ['ammotype'] = nil, ['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_dildo')] 				 = {['name'] = 'weapon_dildo', 			['label'] = 'Dildo', 				['weapontype'] = 'Melee',			['maxammo'] = 50, ['ammotype'] = nil, 			['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[GetHashKey('weapon_flashbang')] 				 = {['name'] = 'weapon_flashbang', 			['label'] = 'weapon_flashbang', 				['weapontype'] = 'Throwable',			['maxammo'] = 50, ['ammotype'] = nil, 			['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	
}
