AddTextEntry("weapon_groza", "GROZA")
AddTextEntry("weapon_gepard", "GEPARD")
AddTextEntry("weapon_dildo", "DILDO")
AddTextEntry("weapon_dp9", "DP9")
AddTextEntry("weapon_g18c", "G18C")
AddTextEntry("weapon_krambit", "KRAMBIT")
AddTextEntry("weapon_mp5", "MP5")
AddTextEntry("weapon_sword", "Sword")
AddTextEntry("weapon_m67", "M 67")
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_FNX45", "FN FNX45")
AddTextEntry("WEAPON_HUNTINGRIFLE", "Hunting Rifle")
AddTextEntry("WEAPON_M70", "M70")
AddTextEntry("WEAPON_MK14", "MK14")
AddTextEntry("WEAPON_MOSSBERG", "Mossberg 500")
AddTextEntry("WEAPON_REMINGTON", "Remington 870")
AddTextEntry("WEAPON_SCARH", "SCAR-H")
AddTextEntry("WEAPON_SHIV", "Shiv")
AddTextEntry("WEAPON_SLEDGEHAMMER", "Sledge Hammer")
AddTextEntry("WEAPON_M110", "M110")
AddTextEntry("WEAPON_HK416", "HK-416")
